import gameController.GameController;


/*
NEXT PROJECT STEP:
FIX CHECK RUN SO THAT CODE IS NOT COPPY PASTED FOR DIAMONDS
ADD LOGIC FOR COUNTING 9S TO CHECK RUN AND CHECK LONG SUIT SO DISPLAYING MELD ISNT A HASSLE
WORK ON DISPAYING MELD FOR EACH PLAYER

THINGS TO GO BACK AND LOOK AT:
TRY RANDOMIZING THE INDEX IN DEAL TO GENERATE BETTER HANDS
*/

public class Driver {
	
	public static void main(String[] args)
	{
		
		GameController.Start();
	}
	
}
